version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          namae: Install Deps
          command: yarn
workflow:
    version: 2
    test:
        jobs:
           - build_and_test          
